version: '2'
services:
  application:
    build: ./
  mysql:
    image: mostad/mysql
    ports:
      - "3306:3306"
  nginx:
    image: mostad/nginx
    depends_on:
      - application
      - mysql
      - php
    ports:
      - "80:80"
      - "443:443"
    volumes_from:
      - application
  php:
    image: mostad/php-fpm
    ports:
      - "9000"
    volumes_from:
      - application
