version: '2'
services:
  application:
    build: ./
    depends_on:
      - mysql
  mysql:
    image: mostad/mysql
    ports:
      - '3306:3306'
  nginx:
    image: nginx:1.10
    depends_on:
      - application
    links:
      - 'application:php-fpm'
    ports:
      - '80:80'
      - '443:443'
    volumes_from:
      - application
